mcscanx: struct.cc mcscan.cc read_data.cc out_utils.cc dagchainer.cc permutation.cc	
	g++ struct.cc mcscan.cc read_data.cc out_utils.cc dagchainer.cc permutation.cc -o MCScanX
	javac annotate_tree_with_dup_modes.java annotate_tree_with_tra_dup.java node.java branch.java rt.java Cubic.java

